# Generated by Django 3.1.7 on 2021-11-24 05:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portifolio_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_name', models.CharField(blank=True, default='Hello, I’m Fatima.', max_length=256, null=True)),
                ('our_profession', models.CharField(blank=True, default='FREELANCE DIGITAL DESIGNER', max_length=256, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=256, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='portifolio/backgroundImage/')),
                ('download_cv_file', models.FileField(blank=True, null=True, upload_to='portifolio/cv/', validators=[django.core.validators.FileExtensionValidator(['csv', 'docx'])])),
                ('download_cv_url', models.CharField(blank=True, max_length=256, null=True)),
                ('download_cv_button', models.CharField(blank=True, default='DOWNLOAD CV', max_length=256, null=True)),
                ('about_heading', models.CharField(blank=True, default='My About', max_length=256, null=True)),
                ('about_subtitle', models.CharField(blank=True, default='Read About Me', max_length=256, null=True)),
                ('about_content', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='portifolio/aboutImage/')),
                ('client_heading', models.CharField(blank=True, default='My Top Clients', max_length=256, null=True)),
                ('client_subtitle', models.CharField(blank=True, default='Clients Meeting With Me', max_length=256, null=True)),
                ('client_video_file', models.FileField(blank=True, null=True, upload_to='portifolio/client_video/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('client_video_id', models.URLField(blank=True, null=True)),
                ('performance_heading', models.CharField(blank=True, default='My Best Performance', max_length=256, null=True)),
                ('performance_subtitle', models.CharField(blank=True, default='My Performance', max_length=256, null=True)),
                ('performance_content', models.TextField(blank=True, null=True)),
                ('performance_image', models.ImageField(blank=True, null=True, upload_to='portifolio/performanceImage')),
                ('performance_button', models.CharField(blank=True, default='SEE MY SKILL', max_length=256, null=True)),
                ('project_heading', models.CharField(blank=True, default='Our Project', max_length=256, null=True)),
                ('project_sub_heading', models.CharField(blank=True, default='Some of My Recent Works', max_length=256, null=True)),
                ('project_subtitle', models.CharField(blank=True, default='There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration.', max_length=256, null=True)),
                ('project_button', models.CharField(blank=True, default='VIEW PROJECTS', max_length=256, null=True)),
                ('contact_heading', models.CharField(blank=True, default="Let's Say Hi", max_length=256, null=True)),
                ('contact_sub_heading', models.CharField(blank=True, default='Hire Me.', max_length=256, null=True)),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='portifolio/contactImage')),
                ('call_number_heading', models.CharField(blank=True, default='Call us directly : ', max_length=256, null=True)),
                ('email_heading', models.CharField(blank=True, default='Contact Email : ', max_length=256, null=True)),
                ('contact_button', models.CharField(blank=True, default='SUBMIT NOW', max_length=256, null=True)),
                ('page_end_title', models.CharField(blank=True, default='Ready to start creating a standard website?', max_length=256, null=True)),
                ('page_last_button', models.CharField(blank=True, default='SUBMIT NOW', max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Portifolio Page',
            },
        ),
    ]
