# Generated by Django 3.1.7 on 2021-11-24 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_portifolio_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='educational_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Educational Skill', max_length=256, null=True)),
                ('subtitle', models.CharField(blank=True, default='Lorem ipsum dolor sit amet, onecis et mollis.', max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Educational Skills',
            },
        ),
        migrations.CreateModel(
            name='our_clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=256, null=True)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='clients/logo/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Our Clients',
            },
        ),
        migrations.CreateModel(
            name='our_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=256, null=True)),
                ('project_subtitle', models.CharField(blank=True, max_length=256, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project/image/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Our Projects',
            },
        ),
    ]
