# Generated by Django 3.1.7 on 2021-11-24 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_educational_skills_our_clients_our_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolio_page',
            name='download_cv_file',
            field=models.FileField(blank=True, null=True, upload_to='portifolio/cv/', validators=[django.core.validators.FileExtensionValidator(['csv', 'docx', 'pdf'])]),
        ),
    ]
