# Generated by Django 3.1.7 on 2021-11-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_auto_20211124_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolio_page',
            name='project_heading',
            field=models.CharField(blank=True, default='Some of My Recent Works', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='portifolio_page',
            name='project_sub_heading',
            field=models.CharField(blank=True, default='Our Project', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='basic/logo/'),
        ),
    ]
