# Generated by Django 3.1.7 on 2021-11-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_contact_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_form',
            new_name='lead_contacts',
        ),
    ]
