# Generated by Django 3.1.7 on 2021-12-29 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_auto_20211229_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_projects',
            name='project_Video_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/video/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
