# Generated by Django 3.1.7 on 2021-12-29 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_auto_20211229_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='lead_contact_numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('generatedFrom', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Lead Contact Numbers',
            },
        ),
    ]
