# Generated by Django 3.1.7 on 2021-12-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0012_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_projects',
            name='project_Video_file',
        ),
        migrations.RemoveField(
            model_name='our_projects',
            name='project_video_id',
        ),
        migrations.RemoveField(
            model_name='our_projects',
            name='video_heading',
        ),
    ]
