# Generated by Django 3.1.7 on 2021-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0013_auto_20211229_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
