# Generated by Django 3.1.7 on 2021-12-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0015_auto_20211229_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_contacts',
            name='generatedFrom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
