# Generated by Django 3.1.7 on 2021-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0017_auto_20211230_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='our_work_Video',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
