# Generated by Django 3.1.7 on 2021-12-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolioApp', '0018_videos_our_work_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleType', models.CharField(blank=True, choices=[('ERROR', 'ERROR'), ('SUCCESS', 'SUCCESS'), ('WARNING', 'WARNING'), ('THANKYOU', 'THANKYOU')], max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorMM', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Message Model Content',
            },
        ),
    ]
