# Generated by Django 3.1.7 on 2021-12-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0019_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='titleType',
            new_name='messageFor',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
